Fix an issue in the query test using manufactured solution
When increasing the problem size from 11^3 to 51^3 in the manufactured
solution test, it failed:
```
../test/tstQueryTreeManufacturedSolution.cpp(254):
error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX__BoundingVolumeHierarchy, Kokkos__Device<Kokkos__Serial, Kokkos__HostSpace> >>":
check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
Mismatch at position 107186: ( 85094 87695 ) != ( 85094 ).
Mismatch at position 111824: ( 122546 125147 ) != ( 122546 ).
```
A query could find multiple points if the query box was aligned with one
of the grid lines, or close to it.

This patch changes the way we generate the random queries to make sure
each query does not get too close to a grid line, thus guaranteeing a
single result.